# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-3.0-or-later
version = 1
SPDX-PackageName = "NextcloudCapabilitiesKit"
SPDX-PackageSupplier = "2025 Nextcloud GmbH and Nextcloud contributors"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud/NextcloudCapabilitiesKit"

[[annotations]]
path = [
    "NextcloudCapabilitiesKit.png", 
    "NextcloudCapabilitiesKit.pxd", 
    "NextcloudCapabilitiesKit.svg"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Nextcloud GmbH"
SPDX-License-Identifier = "LicenseRef-NextcloudTrademarks"

[[annotations]]
path = [
    ".swiftformat",
    ".swift-version"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Nextcloud GmbH"
SPDX-License-Identifier = "LicenseRef-NextcloudTrademarks"