# SPDX-FileCopyrightText: Nextcloud GmbH
# SPDX-FileCopyrightText: 2025 Iva Horn
# SPDX-License-Identifier: LGPL-3.0-or-later

name: Xcode

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Tests:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Run Tests
      run: xcodebuild clean build test -scheme NextcloudCapabilitiesKit -destination "platform=macOS,name=My Mac"

